services:

  judge:
    build:
      dockerfile: docker/server/Dockerfile
      context: ..
    restart: unless-stopped
    user: "root:root"
    volumes:
      - ../test_cases:/test_cases
      - judge:/db
      - repos:/repos
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GITEA_URL=${GITEA_URL:-http://gitea:3000}
      - GITEA_TOKEN=${GITEA_TOKEN}
      - GITEA_WEBHOOK_SECRET=${GITEA_WEBHOOK_SECRET:-anExampleSecret}
      - BASE_URL=${BASE_URL:-http://localhost:3000}
      - DOCKER_IMAGE=${DOCKER_IMAGE:-}
      - LOG_LEVEL=6
      - MAX_PARALLEL_JUDGES=5
      - TESTS_PATH=/test_cases
      - DB_PATH=/db
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3010:3000"
      - "222:22"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

volumes:
  judge:
  gitea:
  repos:
