services:
  judge:
    image: ghcr.io/gurkengewuerz/gitcodejudge-server:latest
    restart: unless-stopped
    networks: [traefik]

    volumes:
      - ${CONTAINER_DIR}/judge/tests:/test_cases
      - ${CONTAINER_DIR}/judge/db:/db
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BASE_URL=https://$VIRTUAL_HOST
      - GITEA_URL=$GITEA_URL
      - GITEA_TOKEN=$GITEA_TOKEN
      - GITEA_WEBHOOK_SECRET=$GITEA_WEBHOOK_SECRET
      - LOG_LEVEL=4
      - MAX_PARALLEL_JUDGES=5
      - TESTS_PATH=/test_cases
      - DB_PATH=/db
      - PDF_FOOTER_COPYRIGHT=Copyright by Gurkengewuerz
      - LEADERBOARD_ENABLED=true
      - OAUTH2_ISSUER=${OAUTH2_ISSUER:-}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID:-}
      - OAUTH2_SECRET=${OAUTH2_SECRET:-}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.gitjudge.entrypoints=websecure"
      - "traefik.http.routers.gitjudge.rule=HOST(`$VIRTUAL_HOST`)"
      - "traefik.http.routers.gitjudge.service=gitjudge-srv"
      - "traefik.http.services.gitjudge-srv.loadbalancer.server.port=3000"
    logging:
      driver: "json-file"
      options:
        max-size: "512k"
        max-file: "1"

networks:
  traefik:
    external: true
