disabled: false
name: "Pascal's Triangle"
description: |
    Generate Pascal's Triangle with n rows and format it to look like a proper triangle.
    Each number should be properly spaced and centered.
    
    Input format:
    - Single integer n (1 ≤ n ≤ 15) representing the number of rows
    
    Output format:
    - n lines representing Pascal's Triangle
    - Each line should be properly centered
    - Numbers in each row should be space-separated
    - The entire triangle should be centered

start_date: 2024-01-02T15:04:05Z
end_date: 2030-12-31T15:04:05Z

cases:
    - input: |
          5
      expected: |
       .
            1
           1 1
          1 2 1
         1 3 3 1
        1 4 6 4 1
    
    - input: |
          3
      expected: |
       .
         1
        1 1
       1 2 1

hidden_cases:
    - input: |
          1
      expected: |
          1
    
    - input: |
          4
      expected: |
       .
          1
         1 1
        1 2 1
       1 3 3 1

    - input: |
          6
      expected: |
          .
                  1
                1  1
               1  2  1
             1  3  3  1
            1  4  6  4  1
          1  5  10 10 5  1
